version: '2'

services:
  consul1:
    image: consul:1.6.0
    command: 'agent -server -bootstrap-expect=3 -ui -client=0.0.0.0 -node=consul1 -log-level=debug'
    ports:
      - '8300:8300'
      - '8301:8301'
      - '8302:8302'
      - '8400:8400'
      - '8500:8500'
      - '8600:8600'
#      - '8600:53/udp'
#      - "53:8600/udp"
    container_name: 'consul1'
    networks:
      docker-consul:
        ipv4_address: 172.16.238.10

  consul2:
    image: consul:1.6.0
    command: 'agent -server -retry-join consul1 -node=consul2 -log-level=debug'
    container_name: 'consul2'
    depends_on:
      - consul1
    networks:
      docker-consul:
        ipv4_address: 172.16.238.11

  consul3:
    image: consul:1.6.0
    command: 'agent -server -retry-join consul1 -node=consul3 -log-level=debug'
    container_name: 'consul3'
    depends_on:
      - consul1
    networks:
      docker-consul:
        ipv4_address: 172.16.238.12

  nginx1:
    image: nginx:1.17.3
    ports:
      - '8080:80'
    environment:
      - NGINX_PORT=80
    container_name: 'nginx1'
    depends_on:
      - consul1
    networks:
      docker-consul:
        ipv4_address: 172.16.238.13

  nginx2:
    image: nginx:1.17.3
    ports:
      - '8000:80'
    environment:
      - NGINX_PORT=80
    container_name: 'nginx2'
    depends_on:
      - consul1
    networks:
      docker-consul:
        ipv4_address: 172.16.238.14

  nginx3:
    image: nginx:1.17.3
    ports:
      - '8888:80'
    environment:
      - NGINX_PORT=80
    container_name: 'nginx3'
    depends_on:
      - consul1
    networks:
      docker-consul:
        ipv4_address: 172.16.238.15

networks:
  docker-consul:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1